########################################
## Set up TStarJetPico library environment
## STARPICODIR or STARPICOPATH have to be set as an environment variable
SET ( TSTARJETPICO_LIBRARY TStarJetPico )

## find the relevant environment variable
IF ( DEFINED ENV{STARPICOPATH} )
SET (STARPICO_LOCAL $ENV{STARPICOPATH} )
ELSEIF ( DEFINED ENV{STARPICODIR} )
SET (STARPICO_LOCAL $ENV{STARPICODIR} )
ENDIF ( DEFINED ENV{STARPICOPATH} )


UNSET ( lib CACHE )
FIND_LIBRARY( lib TStarJetPico PATHS ${STARPICO_LOCAL} NO_DEFAULT_PATH )
FIND_LIBRARY( lib TStarJetPico )

IF ( lib )
SET ( TSTARJETPICO_LIB_PATH ${TSTARJETPICO_LIB_PATH} ${STARPICO_LOCAL} )
SET ( TSTARJETPICO_INCLUDE_PATH ${TSTARJETPICO_INCLUDE_PATH} ${STARPICO_LOCAL} )
MESSAGE ( STATUS "Found TStarJetPico" )
ELSE()
MESSAGE ( FATAL "Can't Find TStarJetPico" )
ENDIF ( lib )

## Add TStarJetPico include path to cmake
INCLUDE_DIRECTORIES ( ${TSTARJETPICO_INCLUDE_PATH} )
LINK_DIRECTORIES ( ${TSTARJETPICO_LIB_PATH} )
